import Head from 'next/head'
// import Image from "next/image";
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jair Alcon Photography</title>
        <meta
          name="Photography Website"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Jair Alcon | Photography"
        message="I capture life moments and help keep the record of time."
      />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  )
}
